-- ====================================================
-- Crear la base de datos
-- ====================================================
use master
go
if exists (select * from sysdatabases where name='DBGestionTesis')
begin 
    drop database DBGestionTesis
end
go
--Crear la Base de Datos
Create DATABASE DBGestionTesis
go
/* Activar Base de datos:  */
use DBGestionTesis
go

/* Crear las tablas*/
-------------------------------------------------------------------
create table TTesista
(
    CodAlumno       varchar(10) check (CodAlumno like '[0-9][0-9][0-9][0-9][0-9][0-9]'),
	Nombres          varchar(80) NOT NULL,
	Apellidos       varchar(100) NOT NULL,
	TipoAlumno      varchar(80) check (TipoAlumno in ('REGULAR','BACHILLER')),
	EscuelaProfesional    varchar(80) check (EscuelaProfesional in ('INGENIERIA INFORMATICA Y DE SISTEMAS')),
	
	-- definición de claves
    PRIMARY KEY (CodAlumno)
)
go
---------------------------------------------------------------------
create table TDocente
(
    CodDocente      varchar(10) check (CodDocente like '[0-9][0-9][0-9][0-9][0-9][0-9]'),
	Nombres          varchar(30) NOT NULL,
	Apellidos       varchar(100) NOT NULL,
	Tipo           varchar(40) check (Tipo in ('CONTRATADO','NOMBRADO')),
	DepartamentoAcademico      varchar(150) check (DepartamentoAcademico in ('INGENIERIA INFORMATICA','INGENIERIA MECANICA','INGENIERIA ELECTRICA','INGENIERIA ELECTRONICA')),
	-- definición de claves
    PRIMARY KEY (CodDocente)
)
go
--------------------------------------------------------------------
create table TUsuarioAdministrativo
(
    CodUsuario      varchar(10) check (CodUsuario like '[U][0-9][0-9][0-9][0-9][0-9][0-9]'),
	Nombres          varchar(50) NOT NULL,
	Apellidos       varchar(100) NOT NULL,
	CargoAdministrativo       varchar(20) NOT NULL,
	Contraseña		varchar(10),
	-- definición de claves
    PRIMARY KEY (CodUsuario)
	
)
go
---------------------------------------------------------------------
create table TTesis
(
    CodTesis        varchar(10) check (CodTesis like '[T][0-9][0-9][0-9][0-9][0-9][0-9]'),
	Titulo          varchar(200) NOT NULL,
	CodDocente      varchar(10),
	-- definición de claves
    PRIMARY KEY (CodTesis),
	FOREIGN KEY (CodDocente) references TDocente,
)
go
-------------------------------------------------------------------
create table TTesista_Tesis
(
	CodAlumno  varchar(10),
	CodTesis   varchar(10),
	-- definición de claves
    PRIMARY KEY (CodAlumno,CodTesis),
	FOREIGN KEY (CodAlumno) references TTesista,
	FOREIGN KEY (CodTesis) references TTesis,
)
go
-------------------------------------------------------------------
create table TTipoTramite
(
    CodTipoTramite   varchar(10) check (CodTipoTramite like '[T][R][0-9][0-9][0-9][0-9][0-9][0-9]'),
	Nombre           varchar(100) NOT NULL,
	-- definición de claves
    PRIMARY KEY (CodTipoTramite),
)
go
-------------------------------------------------------------------
create table TRequisito
(
    CodRequisito     varchar(10) check (CodRequisito like '[R][E][Q][0-9][0-9][0-9][0-9][0-9][0-9]'),
	Nombre           varchar(100) NOT NULL,
	-- definición de claves
    PRIMARY KEY (CodRequisito),
)
go
create table TTipoTramite_Requisitos
(
	CodRequisito varchar(10),
	CodTipoTramite  varchar(10),
	-- definición de claves
    PRIMARY KEY (CodTipoTramite,CodRequisito),
	FOREIGN KEY (CodTipoTramite) references TTipoTramite,
	FOREIGN KEY (CodRequisito) references TRequisito,
)
go
-------------------------------------------------------------------
create table TExpediente
(
    CodExpediente   varchar(10) check (CodExpediente like '[E][0-9][0-9][0-9][0-9][0-9][0-9]'),
	Fecha           varchar(100) NOT NULL,
	Estado          varchar(100) NOT NULL,
	CodTesis        varchar(10),
	CodTipoTramite  varchar(10),
	-- definición de claves
    PRIMARY KEY (CodExpediente),
	FOREIGN KEY (CodTipoTramite) references TTipoTramite,
	FOREIGN KEY (CodTesis) references TTesis,
)
go

-------------------------------------------------------------------


-------------------------------------------------------------------
create table TExpedienteAsignacion	
(
    CodExpedienteAsignacion	           varchar(10) check (CodExpedienteAsignacion like '[E][A][0-9][0-9][0-9][0-9][0-9][0-9]'),
	Fecha                              varchar(100) NOT NULL,
	CodExpediente                      varchar(10),
	-- definición de claves
    PRIMARY KEY (CodExpedienteAsignacion),
	FOREIGN KEY (CodExpediente) REFERENCES TExpediente,
)
go

-------------------------------------------------------------------
create table TExpedienteAsig_Docente	
(
	CodExpedienteAsignacion             varchar(10),
	CodDocente                          varchar(10),
	Rol                                 varchar(100) NOT NULL,
	-- definición de claves
    PRIMARY KEY (CodExpedienteAsignacion,CodDocente),
	FOREIGN KEY (CodExpedienteAsignacion) REFERENCES TExpedienteAsignacion,
	FOREIGN KEY (CodDocente) REFERENCES TDocente,
)
go

-------------------------------------------------------------------

create table TResolucionJurado
(
    CodResolucionJurado	   varchar(10) check (CodResolucionJurado like '[R][J][0-9][0-9][0-9][0-9][0-9][0-9]'),
	FechaResolucion                   varchar(100) NOT NULL,
	Lugar                             varchar(100),
	FechaSustentacion                 varchar(100),
	HoraSustentacion                  varchar(100),
	CodExpediente                      varchar(10),
	-- definición de claves
    PRIMARY KEY (CodResolucionJurado),
	FOREIGN KEY (CodExpediente) REFERENCES TExpediente,
)
go

-------------------------------------------------------------------
create table TExpedienteAsig_DocenteJurado	
(
	CodResolucionJurado       varchar(10),
	CodDocente                          varchar(10),
	Rol                                 varchar(100),
	-- definición de claves
    PRIMARY KEY (CodResolucionJurado ,CodDocente),
	FOREIGN KEY (CodResolucionJurado ) REFERENCES TResolucionJurado ,
	FOREIGN KEY (CodDocente) REFERENCES TDocente,
)
go
-------------------------------------------------------------------
create table TActaSustentacion
(
	CodActaSustentacion                 varchar(10) check (CodActaSustentacion like '[A][0-9][0-9][0-9][0-9][0-9][0-9]'),
	FechaSustentacion                   varchar(40) NOT NULL,
	HoraDeInicio                        varchar(100) NOT NULL,
	HoraFinalizacion                    varchar(100) NOT NULL,
	NotaNro                             varchar(20) NOT NULL,
	NotaFinal                           varchar(20) NOT NULL,
	CodExpediente                       varchar(10),

	-- definición de claves
    PRIMARY KEY (CodActaSustentacion),
	FOREIGN KEY (CodExpediente) REFERENCES TExpediente,
)
go
-------------------------------------------------------------------
-------------------------------------------------------------------

create table TInformeEvaluacion
(
    CodInformeEvaluacion           varchar(10) check (CodInformeEvaluacion like '[I][E][0-9][0-9][0-9][0-9][0-9][0-9]'),
	Tipo                           varchar(20) NOT NULL,
	Fecha                          varchar(50) NOT NULL,
	Observaciones                  varchar(100) NOT NULL,
	CodDocente                     varchar(10),
	NotaNro                        varchar(20) NOT NULL,
	NotaText                       varchar(20) NOT NULL,
	CodExpediente                  varchar(10),
	-- definición de claves
    PRIMARY KEY (CodInformeEvaluacion),
	FOREIGN KEY (CodDocente) REFERENCES TDocente,
	FOREIGN KEY (CodExpediente) REFERENCES TExpediente,
)
go

-------------------------------------------------------------------
create table TResolucion	
(
    CodResolucion               varchar(10) check (CodResolucion like '[R][0-9][0-9][0-9][0-9][0-9][0-9]'),
	Tipo                  varchar(100) NOT NULL,
	Fecha                 varchar(40) NOT NULL,
	NotaFinal             varchar(20) NOT NULL,
	CodExpediente        varchar(10),
	-- definición de claves
    PRIMARY KEY (CodResolucion),
	FOREIGN KEY (CodExpediente) REFERENCES TExpediente,
)
go


-------------------------------------------------------------------
--Insersion de datos
set dateformat dMy
go

-----ejemplos ------------------
-------------------------------------------------------------------
-- inserción de datos en la tabla Tesista 
-------------------------------------------------------------------
insert into TUsuarioAdministrativo values('U123456','LUCIA','ALVARADO VALDEZ','ADMI','123456')
-------------------------------------------------------------------
-- inserción de datos en la tabla Tesista --
-------------------------------------------------------------------
insert into TTesista values('184211','JHON JAIME','TINCUSI CCORIMANYA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('183485','JOSE ANTONIO','SULLCA AQUINO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('193002','ADELMECIA','MERCADO HUAYCHO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('114136','JUAN RAISER','ALMIRON GONZALES','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('155193','JAVIER JAIL','CORNEJO PILLCO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('193168','FREDIMAR','ESPINOZA OTAZU','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171070','MELANIE INDIRA','SULLCA PERALTA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160327','KEVIN YEISON','CUSI HUAMAN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('192422','ANDY MARCELO','HUAMAN QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184656','MARCELO EDUARDO','SUAREZ MARISCAL','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('164817','TANY ARISTIDES','HUAYHUA JURADO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('194520','FRANKLIN','LLAMOCCA QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('103172','ANGEL','PALOMINO POVEA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('163810','YOFRE','RODRIGUEZ HUARACA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182932','JHON ALBERTH','QUISPE QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('151780','LUCERO','QUISPE PUMA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184201','LUIS FERNANDO','GUTIERREZ TAQQUERE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('163809','RUBEN','MAMANI CHINO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('124799','CARLOS ALEX','NINA GUARDAPUCLLA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('164238','EVANDIR SAUL','CASILLA TTITO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('154634','DANIEL','MOSQUEIRA OBANDO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('150404','CAYO ABEL','QUEKQA�O QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('151829','PAMELA','DELGADO HERRERA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('143833','RAUL ELVER','MELO GUTIERREZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('194527','YOEL SANDRO','QUISPE SANTA CRUZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184765','JOSE ANTONIO','CONDORI TUNQUIPA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('155183','JEREMYK RUFINO','VARGAS ARQQUE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('163525','GABRIELA','FARFAN ENRIQUEZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174864','DANNY','RAMOS CONDORI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('163845','VICTOR POOL','HUILLCA HERRERA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160888','ORLANDO','CANA APU','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('170431','JOSE LUIS','CRUZ CARRION','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('194922','ESTEFAN POL','SILVA GUEVARA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182921','ALVARO SEBASTIAN','MOLLINEDO PE�A','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('111868','GUIDO','VICENTE RAMIREZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171565','CHRISTIAN FERNANDO','MU�OZ PACHECO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('192423','JHON ANTHONY','LOPEZ BARAZORDA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('193001','EDUARDO JUAREIS','GIFONE VILLASANTE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('144989','HILSTON WILL','CALLA�AUPA CHIHUANTITO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('155192','ALFREDO','NU�EZ HUALLA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('101658','DENNIS ALIPIO','CHOQUE CCOA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('161368','CHARLIE JOEL','LUNA CCASANI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('145003','HECTOR PAOLO','BARAZORDA CUELLAR','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171062','JUAN MANUEL','GUTIERREZ SALAZAR','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('155186','JHON ALFRED','ALARCON MAMANI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184194','FERDINAN JUNIOR','CONDORCAHUA AYLLONE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171069','JORGE VICTOR','RODRIGUEZ OJEDA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('183218','DIEGO','QUISPE MENDOZA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184191','ARTURO','ALVAREZ MEJIA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('121957','ERNESTO FRANCISCO','ARANGURE TORRES','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('124815','CATHERINE LIZBED','LOAYZA CONDOR','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('120879','RUBEN','ANCCO PERALTA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('163671','ANGELO','ROBLES SILVA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('164235','JOSUE CRISTIAN','CALLAPI�A RODRIGUEZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('113553','IGNACIO','FLORES YUCRA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('151336','JULIO CESAR','HUILLCA COLQUE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('191873','GLINA DE LA FLOR','PUMA HUAMANI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('194516','ELIAZAR','CCA�IHUA LAYME','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('193807','CESAR AUGUSTO','JANCCO CONCHA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('951304','NOHEMI','SALCE MEJIA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174909','LEYDI DIANA','CHOQUE SARMIENTO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171916','RICHARD MIKHAEL','PEREIRA CHINCHERO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171866','RONALDO','QUISPE YAHUIRA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174439','NORGAN SANDRO','CHOQUECONZA QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('141154','CHRIS  IALEEN','FERNANDEZ TILCA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('163812','NESTOR','VIZA AEDO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174838','OSBALDO DAN','CALLHUA ALDAZABAL','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171943','ERICK ANDREW','BUSTAMANTE FLORES','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('193000','ALEJANDRO MIGUEL','CHOQUELUQUE GARCIA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174448','JUAN JOSE','QUISPE MA�ACCASA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('130737','JHOHELLS ERICK','DIANDERAS LOPEZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('150495','SAMAN','QUISPE CLEMENTE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('131444','GABRIEL EDUARDO','ORTIZ RAURAU','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171524','LEONARDO CHEPPER','PUMACAHUA APAZA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('183885','HILDEMARO','CHILE QUIROGA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('144992','JIMY NICANOR','QUINTANILLA CERON','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('194519','JEMY SANDRO','HUAMAN QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('141005','NILTHON JAIR','FLORES MONTOYA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184653','MARJORIE REBECCA','RODRIGUEZ CASAS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('145007','EDMUNDO','ARIAS ORTIZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('192975','GEORGE ALEXANDER','ZAPANA FLORES','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('170439','LUIS ANGEL','QUISPE YNGA CALLA�AUPA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('161764','MARITZA FLOR','SALAS HUAMANI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('170438','JEFERSSON','MAMANI ZANABRIA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('192665','ROYER FUNACOSHI','FERNANDEZ MANDURA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('170749','KENNY HAROLD','CARMONA CHOQUEMAMANI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('150379','JOEL','QUISPE QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('170428','EDWAR YURI','CASSA LIPA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('161757','JHON ALBERT','CCUITO QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182937','HANS ROBERT','VELASQUEZ DURAND','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('113567','IVAN ARTHUR','QUISPE HUARHUA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160541','BRANDON RODRIGO','AYME CONDORI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('193830','CRISTHIAN','CCALA HUAMANI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('103179','ALDO','YARANGA ACHAHUI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('120886','FREDY JULMER','GALLEGOS QUI�ONES','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160543','DIEGO YOSHIRO','DONGO ESQUIVEL','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('194919','WILBER EMANUEL','HUAICOCHEA CARDENAS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('183464','STIWARTH D�ALENBERT','MALDONADO CARDE�A','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184202','ALEXANDER','HANCCO LE�N','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('193835','JERSON EDU','LAVILLA BOLA�OS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('992091','OMAR ROLANDO','CRUZ ZAMALLOA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174450','WILLIAN','SALAS CCOLQQUE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('154623','HEDDED JOEL','SOTO MAMANI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('164245','JHOSET DAVID','NINA GUARDAPUCLLA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('103644','EDER PAUL','LARICO RODRIGO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171060','KEVIN HERNAN','FUENTES CCORI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('111649','ARTHUR DAVIS','HUAYACONZA CONDORI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160332','MIGUEL ANGEL','QUISPE JIMENEZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160895','LEANDRO','TTITO ENRIQUEZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('193027','CARMEN GUADALUPE','BLANCO MOZO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('161369','WILY RODRIGO','MU�OZ MU�OZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('192997','RUTH MILAGROS','ARCE QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('164247','CARLOS ANDRES','PAREDES CARRASCO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('112207','WALDO ERICK','IBARRA CASTILLO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('163807','MILTON ANDERSON','CHATA HUALLPAYUNCA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('170594','DIEGO ALONSO','DORADO TORRES','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184205','WILDER FIDEL','JALISTO ROMERO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171068','RUDY  RODRIGO','RODRIGUEZ HANCCO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160542','ADHAIR EDHINO','C�CERES HUANCA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('145213','LIDER','CONDORI HUILLCA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('164246','JEAN MARCO','PACHA QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184689','LISBETH','PILLCO FLORES','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('113562','ELISBAN','MENDOZA HUAILLAPUMA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('194524','CRISTINA','MELENDRES PEREZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174445','RODRIGO FABRICIO','OLARTE CASAS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182909','JAMES KEVIN','ESTRELLA VILCA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182928','RICHARD MIHAYLOR','PUMA SOTOMAYOR','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('145001','HERBERTH FITZROY','GARCIA CHURA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('141672','JULIO WILSON','CORNEJO CRUZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('120893','YENI RUTH','PORROA SIVANA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174913','EDWARD BRAYAN','NAOLA PUMA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182898','FIORELLA','CERATI CERRILLO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('194523','JOHANA MARIA','MAMANI MEZA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('141158','CESAR ANDERSSON','SAIRE HANCCO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('100511','JUAN CARLOS','GUTIERREZ AMACHI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('124201','DORIS','CUTIPA QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182902','REINHARD VICENT','CONDE QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184196','GONZALO','CUSI FUENTES','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('133962','NOE FRANKLIN','CHOQUENAIRA QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('170432','GONZALO','GUTIERREZ DAZA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('192430','ABELARDO','TTITO QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('124210','JORGE','POLO DOLMOS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('164243','SEBASTIAN ISRAEL','MACEDO GHEILER','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('130742','DIEGO MARTIN','SALAZAR ORE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('155180','NAOMI ISABEL','MASIAS USCAMAYTA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('154632','WILLIAM RUIZ','CHAMPI PUMA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160328','YONATHAN','HUAMAN CABRERA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('170429','JUAN CARLOS','CONDORI LOPEZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('163842','CARLOS ENRIQUE','FERNANDEZ HUILLCA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('154631','CARLOS ANTONI','NOLASCO SUYO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('144994','DENNYS YUTARO','SULLCAHUAMAN VALDEZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('150401','DENILSON','PARI ARRIAGA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('193110','ASTRID','FIGUEROA RODRIGUEZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('192425','HERBERTH CLAUDD','MAYTA SALAZAR','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174906','FRANK CLINTON','APAZA HUAMANI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('155372','ANGELO PIETRI','KU ANDRADE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('150388','JUAN ANTONIO','CHACON VARGAS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171071','MILAGROS','YARAHUAMAN ROJAS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('131532','DAVIS WASHINGTON','ANTAYHUA SAPILLADO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174961','MIGUEL','VILCAHUAMAN CACERES','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('131605','AMILCAR','AYQUIPA GOMEZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('161756','ANTHONY ALDAIR','CCONISLLA MEDINA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('145010','JAVIER','CHOQUEMAMANI YUCRA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('120285','MIGUEL ANGEL CRISOLOGO','PUMA JARA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('150372','JOSE MARIA','HANCCO CHACO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('144884','JUAN DIEGO','POCCORI ESCALANTE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182942','JUAN MANUEL','ZUNIGA AUCCAHUAQUI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('120275','FELIX MANUEL','CANO FLOREZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184213','DORIAN ROGER','ZAVALA TTITO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182938','EDU RODRIGO','VILLAFUERTE GARCES','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('163811','BETO RONALDO','SENCIA GUTIERREZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174905','GIAN MARCO','AGUILAR MAINICTA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('154856','RONALD','HUAHUATICO SORIA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('175061','NICHOLAS EDWARD','MAMANI ZELA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('164249','ALEXANDER','TTITO SAYA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('133960','ABRAHAN ELIAS','CHAMPI CHAMPI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174907','JEFFERSON LENNART','CAMPOS SEGOVIA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160333','NILSON','REYES VALLE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('191870','YOLMY MILAGROS','CAHUATA LAVILLA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('150400','RICARDO','OCHOA MAMANI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('141010','LUISBERTO','RAMIREZ ALVAREZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('192420','TIRSSA IVONNE','GUEVARA DELGADO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('161727','ENIT','MU�OZ PACHECO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160325','MANUEL ALFREDO','APAZA GARRIDO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182893','JAZMIN','AGUILAR PORCEL','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('130730','JAHIL DANIEL','ALVAREZ CORNEJO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182926','ACCENT BLADIMIR','ORTEGA SULLCACCORI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('192414','CRISTHIAN','BARRIENTOS CRUZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('124821','ETSON RONALDAO','ROJAS CAHUANA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('124205','MARICRUZ','HUAYNAPATA QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174908','VLADIMIR DANTE','CASILLA PERCCA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('144986','HUGO ROBERTO','SOTO COCHAMA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182940','AMARU','VILLASANTE LEON','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('192666','EDWARD','MELENDEZ MENDIGURE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('192417','ANGEL LUIS','CESPEDES VILCA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('151822','NILSON MAURI�O','PUMA MAMANI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184641','RUBEN RONALD','BAUTISTA HUILLCA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('120895','AYRTON','QUISPE PICHUILLA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160544','LUIS ABELARDO','JARA HILLPA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('155185','ARACELY','PEZUA CERNADES','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171059','JOSE LUIS','FLORES IGNACIO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182924','RUTH MERY','MU�OZ QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('161134','MARUJEM LYLIBETH','FERNANDEZ GUTIERREZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174440','GIOVDEY ABRAHAM','CONDORI OCHOA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('131610','GRAITD KATERINE','MEDINA VILLAFUERTE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174452','DANIEL EDUARDO','SARCO JACINTO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174941','RONAL FRANKLIN','CHOQUENAIRA GARCIA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('133970','ANSONY','HUALLPA MIRANO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174447','CARLOS ENRIQUE','QUISPE CHAMBILLA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('101059','RICARDO JORGE','CASTILLO LOPEZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182922','FRANKLIN JESUS','MONTES HUILLCA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('122243','RONNY IBSEN','HUAMAN LOPEZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('133971','ALDAIR','HUARCAYA LEON','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('161133','CESAR FRANCISCO','FARFAN LAZO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('145005','ANDREE YORDAN','QUISPE CORONEL','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171564','LUIS ENRIQUE','FLORES AQUINO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('103181','MARCO AURELIO','ZEGARRA CORIMANYA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('133964','JHENDY EDER','GONZALES MEZA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('120889','ALDO DENNIS','JALLO QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('114146','PERCY BRYAN','JOVE CHIRINOS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('194921','CRISTHIAN','SAMATA PUMAHUALCCA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182727','LUIS FERNANDO','CCAHUANTICO NINAMEZA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('124218','CARLOS ALFONSO','UGARTE LLANCAY','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('150387','JULIO CESAR','CARRILLO INQUILTUPA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('114145','YOVANA','HUARAC SA�AC','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('111856','CARLOS ALFREDO','BACA CHOQUE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174443','JUAN VICTOR','FARFAN MOSCOSO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('192419','YANET','CUSI QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171063','NADIABETH DIANA','MALLQUI APAZA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('150408','JHON EDWIN','TACUSI LAROTA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('194526','JOSE ALEXANDER','QUISPE SALAS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182917','BRUCE MAXIMO','MAMANI GABRIEL','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('154633','BRUNO MOISES','CONDORI CCARHUARUPAY','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('143830','JOHN ALDAIR','AIMA JALISTO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182904','ALEX YTALO','CURO MAMANI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182925','ALER SEBASTIAN','OLIVARES CAMERO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('151828','EDWIN MARCELO','CALDERON COVARRUBIAS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('192664','BRAYAN GUSTAVO','APARICIO CASTILLA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184645','EDWIN BRAYAN','CCOTO MACHACA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('170748','LUIS AUGUSTO','ARAUJO LECHUGA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171258','MELISSA BRIGGITTE','ESPEJO FRANCO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('111864','YULIZA','HUILLCA QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('192427','ERICK NICASIO','PORTILLO HUAMAN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('141670','JAIME ANDREE','HALIRE HUAMAN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182896','HAYDER','AUCCAISE RONCO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('145009','MIGUEL HUMBERTO','YCHU VALENCIA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('151332','SHAROM MITCHEL','NOLAZCO SANDOVAL','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('151834','TANIA VANESSA','HUARANCCA PERALTA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171571','JHON NILSON','ROA LIMACHI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('144996','CRISTIAN FERNANDO','BECERRA YARIN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('130348','LISBETH','ORTOGORIN CONDORI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('140987','ALDAIR WILBERT','VILLARES SUBLE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184655','JERY','SANCA ZEVALLOS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('163839','REISON DARIO','CORAZAO HINOJOSA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160890','MARKO LEUGIM','CORDOVA CASTRO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('121460','ASTRID','QUISPE CHAUCCA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171918','MANUEL HUMBERTO','VELARDE FLORES','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('151812','JUSTINO','FERRO ALVAREZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('193832','PAOLA ANDREA','CORTEZ CCAHUANTICO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('130736','NICO ALVARO','CUTIRE ARCE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174856','KALEB GEDEON','MAMANI HUAMAN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182936','ISAC ANDERSON','USUCACHI ANO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182941','KARLA URBELINDA','YUCA LIMA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184192','LISBETH','ARCE QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('170750','LUIS ALDAIR','CUSIHUAMAN AUCCACUSI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('192415','BRAYAN DANIEL','CARRION QUINTANA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('130347','HENRY','NINA COELLO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('154622','JUAN CARLOS','CONDORI ALCAZAR','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('150390','OMAR DANIEL','CORAHUA VALENCIA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('141664','GEORGE ADOLFO','CONDE PADIN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('150411','EDU','VALLENAS CHOQUECOTA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171259','WIDMAR RAUL','QUISPE LEON','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('124211','DAVIS VLADIMIR','PUMASUPA BALLON','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184780','HAPMYR ERWIN','PAUCCAR BLANCO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160336','MANUEL CAMILO','TRIVE�O GUERRERO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('134033','ROBERT ANDRES','QUISPE USCAMAYTA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('125156','WILLIAMS DENNIS','CONDORI FLORES','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184652','ROSWELL JAIME','PANDO MU�OZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184649','ALVARO','HUACHACA PEDRAZA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('101659','JOSE ADOLFO','FERIA TAPARA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('131614','CARLA FERNANDA','YEPEZ MAQUERA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('120881','MIRIAN CAROLINA','CHANCAYAURI HUAMAN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('144987','NILO FIDEL','MENDOZA CJUIRO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('163813','MARCELO ANGELO','VIZCARRA VARGAS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('193129','KEVIN JHOEL','TTITO HUAMAN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('103170','JONATHAN','MOROCCO LAYME','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('154624','RONY','BOLA�OS CCOPA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('150409','MANUEL DARIO','TTITO RAMOS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('192998','FABRICIO YARED','CARDENAS HUAMAN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('155190','BRAYAN ALEXANDERT','HINOJOSA HUARCA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('130322','BRUNO','PEREZ TOMAYLLA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160337','EFRAIN','VITORINO MARIN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174948','ELVIS','HUAMAN CHILO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184193','YEISON EMERSON','CCOSCCO CHAHUA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('141671','VICTOR ANIVAL','PAREDES DENOS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171605','JERSON','SALINAS ATAUSINCHI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('161761','GROBER ALBERT','HUAMANI SURCO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171573','JOSE ANGEL','YA�EZ TUERO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('183469','GONZALO MARTIN','PIMENTEL FRANCO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182765','IVAN MARIO','SUMIRE HANCCO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('164237','JHOSEP ANTONY','CARRION ACU�A','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184650','JUANA YULIANA','HUARHUA QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('111175','DANIEL ALEXANDER','CARRASCO CUNZA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('141599','JAIME','VENTURA JAUJA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('151836','RIVALDO','ORTEGA ALVAREZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('101036','MARITZA','SIVINCHA OLIVA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160887','FERNANDO RAFAEL','CALLA YARIHUAMAN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('151388','MARIA FERNANDA','CACERES QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171064','ABRAHAM BENJAMIN','ORE GAMARRA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('193004','LENIN JOAQUIN','PARQUE AROSQUIPA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182900','GARY BRIGHAM','CHUNGA CASTILLO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('141660','JAIR FREDERICK','AROSTEGUI CERNA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('134544','EDI FRAI','ZUNIGA HUAMAN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174457','OLIVER STIVEN','VELASQUEZ QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160889','FIORELLA SILVIA','CHOQUE BUENO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160923','NELSON','GONZALES HUISA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184647','CARLOS FABRICIO','FLORES NIETO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171067','HILLARY CRISTINA','QUISPE SERRANO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174944','WESLEY JUANPEDRO','CONDORI MOZO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182935','ERICK','USCACHI CCAPA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('130516','WASHINGTON MARCO','BUSTAMANTE MAMANI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174912','CARLOS EDUARDO','INCA CRUZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('192999','MIGUEL ANGEL','CCONCHO CASTELLANOS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171568','JORDY GERSON','QUINCHO RODRIGUEZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160326','MICHEL','CANO LOAIZA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('154630','YEFER YOSELIN','YUCRA VALDEZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('131612','WILLIANS','MONTA�EZ CHOQUE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('161136','JOSE ROLANDO','TTITO OCSA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171065','GRIMALDO','PUMA CHICLLASTO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('140997','DERICK ADOLPHO','TRIVE�OS CALLER','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182911','GABRIELA','GAMARRA HERRERA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('103640','EDSON ARMANDO','FERNANDEZ CIPRIAN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('193003','ELIAZAR','NOA LLASCCANOA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182927','RAISA MELINA','PE�A LUQUE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174441','RENO MAX','DEZA KACHA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('164563','HAIDER ALEX','CARPIO HERMOZA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('164241','DAVID','GIRALDO ENCISO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('155184','LALO LEONEL','MAMANI CCANAHUIRE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182731','YERSON JOAB','CHIRINOS VILCA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('150389','JHACK STEVEN','CONDE SALLO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171058','ROSMEL URIEL','DEZA CONDORI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('164244','BRAYAN VLADYMIR','MOLOCHO CONDORI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('192424','KAROL GIANELLA','MACCARCCO QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('141011','MARITZA  MARIBEL','SIPAUCAR CONDORI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('152128','KONI INDIRA','ALTAMIRANO ALMIRON','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182934','TEOFILO SOCRATES','SAPACAYO HUAYHUA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('164236','KOSMAR HUGO','CARBAJAL LAURA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182929','ALDAIR','QUISPE ACERO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('155637','NESTOR','CORRALES USCA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('134540','CLINTON EDSON','VILLALBA DELGADO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('140156','JOHAN WILFREDO','HUAMAN MENDOZA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160894','DIEGO ARMANDO','RAMOS CONDORI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('143835','SILVANA','SALAZAR BENAVENTE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184648','EDSON  RAUL','GALICIA CENTENO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('100262','JAIME AMILCAR','CATARI SINSAYA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('170434','ANTONY ISAAC','HUAMAN HERMOZA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184643','NELSON BERTOL','CASTRO HUAYHUA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160920','MARCELO FABIAN','CHOQUE NAVARRO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('150396','JOHN ABDUL','LINARES MIRANO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('155191','VICTOR','URQUIZO CARBAJAL','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('134537','JOSE CARLOS','HUAYTA OBLITAS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('134547','JOSE LUIS','CATUNTA CHUCHULLO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('183078','EDSON LEONID','PHUYO HUAMAN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174454','YUREMA LISBETH','TINTAYA TACO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182920','NOHEMI NATALIA','MERMA HUAMAN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('110597','HOLGUER','LLOCLLE PUMA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('140989','FERNANDO','CALLASACA ACU�A','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182913','JHAMIL JHONATAN','HUAHUALUQUE VARGAS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('161783','LISHIEL','ALVAREZ QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('192426','WENDEL YOVAN','NI�O DE GUZMAN CONDE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('192416','WILMAN','CCASANI HUAMAN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184802','PAUL DAVID','MAMANI LAROTA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('150406','ROGER','SANGA MONRROY','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('101032','MAYKOL LUDING','LOAYZA CALLER','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('170751','JOHN KEVIN','ENRIQUEZ QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('191874','MARKO LEONEL','VALENCIA �AUPA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('133972','CAROL YENY','HURTADO ACHAHUI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('183369','LUZ MARINA','DEL CASTILLO OVALLE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('124203','GRECIA MEDALIHT','GOMEZ GARCIA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('100505','WARREN STEPHEN','ARONI SOTO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('145004','JOSEPH ODE','ESPIRILLA MACHACA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('145000','JIM','C�RDENAS CRUZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('150335','LESLY YAHAIRA','YUCRA TTITO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('154636','JOSE RAMIRO','PALOMINO AUQUITAYASI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('170441','ALEX CHRISTOPHER','VILLAFUERTE TURPO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171805','CLAUDIA LUZ','ROJAS SOTO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184212','LUIS MAO','VALENCIA CUSIPUMA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184654','MIGUEL ENRIQUE','SACA ACCOSTUPA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('194530','NYCOLL TATIANA','ZEVALLLOS VIDAL','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184197','LUCIAN NEPTALI','FERNANDEZ BACA CASTRO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('111332','JOSE WALTHER','QUISPE CALANCHI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('950610','LUIS','ANDRADE ESCOBAR','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('192428','ARTUR MARTI','RADO HUAYOTUMA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('113561','KEVIN ROUSBEL','MAXDEO LAGOS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('130740','ABIGAIL','HUILLCA HUILLCA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('133581','JOSE SAUL','UMERES LOAYZA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('111860','DENNIS ERICK','CHALCO CARRASCO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('194521','CRISTIAN DANIEL','MALDONADO CHALCO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('151775','BRENDA NAHOMI','QUISPE GONZALES','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171914','ALEXANDER JUNIOR','MONZON MONTALVO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182923','LUZ LUCERO','MORA CCARHUARUPAY','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('120283','NELSON','L�PEZ RAMOS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('120883','ALEX SAIN','CJUNO MACHACA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('192418','ANGELA LORENA','CORNEJO CASTRO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171066','LADY DIANA','QUINTO CATACHURA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('140985','JERRY ANDERSON','LIMPE QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('164242','PATRICK ANTONIO','INQUILTUPA CORTEZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('194528','JAIRO','SAIRE MANZANILLA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('185132','GABRIEL ARTURO','MAMANI TAY�A','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('120894','DAVID JESUS','QUISPE CHACO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('141006','SINTIA','LLAMACPONCCA CHUQUIHUAYTA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('194529','GERSON','TORRES MAMANI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('124812','HUBERT RANCES','CANDIA RUBIO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174442','ANGIE','ESCOBEDO MESCCO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('110125','CRISTIAN RODRIGO','LOPINTA HUAMAN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160331','MILTON ADERLIN','MOZO DAVILA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('154635','JOSE ANTONIO','CONDORI HUILLCA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182939','PAMELA ARACELY','VILLALOBOS QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('170435','ALVARO RICARDO','HUAMAN TORRES','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182903','ELMER','CONDORI VALENCIA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('141673','SAMIRE','RAMOS DELGADO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('194920','JUVENAL','HUAMANI CRIOLLO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('103649','PATRICIA','UMERES JIMENEZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('194918','DAYHANA LUCERO','GAMARRA FLORES','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('194525','ARELI SHALON','PAREDES CURASCO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('170436','MARIELA','LUYCHO ANCAIFURO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('110603','FRANK EDISON','PUMAYALLI CUSICUNA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160853','CARLOS EDUARDO','PUMA MENDOZA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('191871','RAY MARCELO','IBARRA HUAMANCARI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('120008','CARLA PALOMA','CUETO SANCHEZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('170433','JULIO JOSUE','HOLGUIN CONDORI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171910','JHON WALDIR','GUERRA BELLIDO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('164248','JOSE FRANCISCO','PUMA POTOCINO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160545','ALEXANDER YERIM','NAOLA PEREYRA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('111651','WILLIAM','QUISPE SOTO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('125110','NAYLUZ ROSMERY','VERA CCASA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('161731','DAVID','SONCCO CACHURA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('151837','HECTOR GONZALO','GUTIERREZ CHAVEZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160891','WILLY ALDAIR','CRUZ BEJAR','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('193834','CRISTIAN AYRTHON','GODOY LACUTA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160892','FREDDY','LIMACHI ORTEGA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('133959','JUAN ABEL','ANCCO PERALTA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('124207','WILIAMS','LETONA ASTO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182910','KATHERYNE SHARMELLY','FLORES ROBLES','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('113572','EDWAR','AUCAPI�A SUVIZARRETA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('175101','CARLA','QUISPE ESCALANTE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('124811','RAQUEL MELISSA','BERRIOS VILLASANTE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182914','ELVIS JORGE','HUAMAN MENDOZA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174054','MARIANA CHASKA','GUTIERREZ PARIGUANA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182894','ANDRES RODRIGO','ANDIA JAEN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('103637','SHUI DANITZA','AMAO SULLCAHUAMAN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('101664','LUIS ALEXEI','QUISPE RODRIGUEZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160329','BRYAN','HUILLCA MOZO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('144202','MAVILA DANITZA','CURSE CACERES','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('151448','JUAN MANUEL','ROMAN CUELLAR','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171057','FALLCHA XIOMARA','CALDERON TINTAYA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174910','MIGUEL ANGEL','CUSI HUAYLLA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160338','HOLGER ALFREDO','YUPANQUI CARRILLO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('100260','KHAROL','CORONEL FERNANDEZ BACA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('140999','ROSARIO','ANCCO PERALTA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('161760','PERCY ELVIS','HUAMAN VARGAS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('175022','OWEN DEISER','BAUTISTA HURTADO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('164567','MELANY FABIOLA','QUISPE CHAUCCA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171572','JORGE ANDRE','SALCEDO HURTADO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('103647','JESUS ADEL','QUISPE ARONI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174446','JAVIER GUSTAVO','PORRAS CHARCA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('155182','RENATO','MAR GIBAJA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184198','DIEGO','FERNANDEZ ALVAREZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('155189','BLADIMIR','HUARAYA CHARA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182912','ANDREE GONZALO','GAMARRA SANCHEZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171061','CRISTIAN LUIS','GUEVARA FERRO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('110071','CIRO','MUNIVE SALAS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184195','EMERSON','CORDOVA CCOPA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('141677','JUAN CARLOS','NINAHUANCA CHOQUE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('124219','MARIA ANGELA','VALLE HUAMAN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('140145','GONZALO AMIR','FLORES MOLINA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('161135','RUDI','QUISPE TACURI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184206','MARCUS GEUSEPPE','MEZA ZAMALLOA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('103171','JHON ANDER','NAHUAMEL SARCE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('194518','NICANOR','HUAMAN JAIMES','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('141631','JHOEL YOJHAN','ABAL VILLASANTE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184203','LISBET PAOLA','HUAMAN ATAYUPANQUI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('130743','DANIEL DARIO','UGARTE FLORES','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('151835','MARCO ANTONIO','HUAMAN LONCONI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('194917','MARY CARMEN','FLORES CASTRO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('120277','EDWIN DENNIS','CASSA LIPA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184644','ENMANUEL JESUS','CCANCHI CONDORI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('161762','ALEX CRISTIAN','MORA HUICHI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184199','LUIS ALBERTO','GALLEGOS CJUIRO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174914','LUIYI ANTONY','QUISPE PALOMINO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('144938','MARISOL ANTONIETA','INFANTAS CHOQUEHUANCA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('170427','ELIZON FRANK','CARCAUSTO MAMANI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171570','EDGAR DANIEL','RAMOS ALVAREZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('154637','JOSUE JOSE','NINA PONCE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('144999','ANIBAL','LIMA RAMOS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('101061','DENNIS','FARFAN LOVON','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('151827','RENAN FERDINAND','LEVA SALAS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('151450','EURIDICE INGRID','ACHAHUANCO ACHAHUI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160886','MARIA LUISA','CACERES LOAYZA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('161765','DANIEL ANTONY','ZU�IGA RAMOS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182901','ALBERTO','COLLANTE CARRASCO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('143832','JAVIER WILLIAN','HUAMAN HUAYLLANI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('160893','LETICIA GIULIANA','OLAZABAL CALLER','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171915','MILEYDY','NINANTAY DIAZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171569','FERNANDO','QUISPE HANCCO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182908','ISRAEL ENRIQUE','ESPINOZA CHAMPI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('161366','LUCIO','GONZALES MANRRIQUE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171260','JOEL WILLY','QUISPE TTITO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('164566','MICHAEL ANTONNI','MAMANI QUINTA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('164240','ROBERTO CARLOS','ESCOBEDO DURAN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182906','DENIS OMAR','CUYO TTITO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('144995','VANESSA','MENDOZA INO�AN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182897','JOSEPH TIMOTHY','CALDERON GARMENDIA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('194916','JEAN MARCO','BACILIO HUAMAN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('124200','PEDRO PABLO','CLAVIJO TITO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('145002','RALEXS','HUALLPA MONTALVO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('133963','FERDINAN','CONSA QQUECCA�O','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('141155','MARGOT','HUAMAN LLAMACPONCCA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('161367','BENJAMIN ALEXANDER','HUALVERDE QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184207','YONATAN','PACCO YLLA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('134538','YONDER','QUISPE CHURA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('134539','WILBERT','TORRES QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('164239','CARLOS DANIEL','CONTRERAS RAMIREZ','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('134134','SAULO SHALON','MELGAREJO SAAVEDRA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('151830','NAJOR JOSUE','VALDEIGLESIAS DUE�AS','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('161759','HUMBERTO','HUACHACA PINEDA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('161758','LUIGGI EDUARDO','FLOREZ CCOA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184646','CHRISTIAN ENRIQUE','DIAZ HUAYLUPO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('163808','ROYER BRANDON','LOZANO LLACCTAHUAMAN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('163806','JHOEL FELIX','ASENCIO ARQQUE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('170430','GEREMY ANDRE','COVARRUBIAS AGUILAR','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('144993','ALEXANDER PAVEL','IBARRA HUAMAN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('155179','YHON LENIN','QUISPE LAROTA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('150394','ALEXANDER JAVIER','HUAMAN GUEVARA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('131050','ALEX','SANDI MAMANI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('154628','CESAR APARICIO','CONDORI HUAYCHAY','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184204','JOEL','HUILLCA QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('171917','SANDRO','RAMOS BANDA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('140934','RONALDINHO','VEGA CENTENO OLIVERA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('164564','ANGEL PLACIDO','ESPINAL HUAMAN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184209','AXEL STEWARF','SAIRE SALAZAR','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174455','BRIGGITTE LEONOR','UGARTE CASTILLO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('150397','BRUNO WALDIR','LOAIZA MONROY','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('141669','NORMANT HAYNOR','BARAZORDA PINO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182899','VANESSA','CHOQUEPATA HUAMAN','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('151833','YURI FERNANDO','CONDE CHURA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('133968','FIORELA ELOISA','SERRANO AMAU','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('141674','KAROL BERLIZ','VILCA PANTIGOSO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('140998','CESAR RODRIGO','TTITO QUILCA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('124813','ALEX ALBERTO','DE LA CRUZ QUISPE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184604','ANTHONY MAYRON','LOPEZ OQUENDO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('134164','IBEHT','TINTAYA TTITO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('150385','JULINHO','APAZA PAREDES','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('150405','MARGOT','QUISPE CONDORI','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('140984','DENNIS MOISES','CCAPATINTA QQUECCA�O','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('170440','JAFET CALEB','ROJAS GARAY','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182916','JEREMY AXL','LAZO MENDOZA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('194522','LUIS ANTHONY','MAMANI MESCCO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('174911','ALEX HELDER','HUANCARA CCOLQQUE','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('182895','IDAHO ANDERSON','AROSTE HURTADO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('184651','ROY MARVIN','MAMANI TAIRO','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')
insert into TTesista values('161365','VERONICA','GALLEGOS HUAYHUA','BACHILLER','INGENIERIA INFORMATICA Y DE SISTEMAS')



go

-------------------------------------------------------------------
-- inserción de datos en la tabla Docente --
-------------------------------------------------------------------
insert into TDocente values('981565','RUDY','GONZALES RAMIREZ','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('981626','BERTA','FLOREZ OCHOA','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('954135','ANA ROCIO','CARDENAS MAITA','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('984445','DENNIS IVAN','CANDIA OVIEDO','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('975423','DORIS SABINA','AGUIRRE CARBAJAL','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('913256','EDWIN','CARRASCO POBLETE','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('973893','EFRAINA GLADYS','CUTIPA ARAPA','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('992815','EMILIO','PALOMINO OLIVERA','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('908451','ENRIQUE','GAMARRA SALDIVAR','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('989878','ESTHER CRISTINA','PACHECO VASQUEZ','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('912321','GUZMAN','TICONA PARI','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('945326','HARLEY','VERA OLIVERA','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('976867','HENRY SAMUEL','DUEÑAS DE LA CRUZ','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('923980','HERMAN','CASTAÑEDA CHIRINOS','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('923544','IVAN CESAR','MEDRANO VALENCIA','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('976899','JAVIER ARTURO','ROZAS HUACHO','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('901054','JAVIER DAVID','CHAVEZ CENTENO','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('909034','JOSE MAURO','PILLCO QUISPE','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('978980','JULIO CESAR','CARBAJAL LUNA','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('914221','KARELIA','MEDINA MIRANDA','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('940221','LAURO','ENCISO RODAS','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('900045','LINO PRISILIANO','FLORES PACHECO','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('989888','LUIS ALVARO','MONZON CONDORI','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('967655','LUIS BELTRAN','PALMA TTITO','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('918381','MANUEL AURELIO','PEÑALOZA FIGUEROA','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('911231','MARITZA KATHERINE','IRPANOCCA CUSIMAYTA','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('909890','NILA ZONIA','ACURIO USCA','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('912311','ROBERT WILBERT','ALZAMORA PAREDES','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('988789','RONY','VILLAFUERTE SERNA','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('933335','VANESA MARIBEL', 'CHOQUE SOTO','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('966668','WALDO ELIO','IBARRA ZAMBRANO','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('999980','WALDO','VILLA RODRIGUEZ','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('911226','WILLIAM','ZAMALOA PARO','NOMBRADO','INGENIERIA INFORMATICA')
insert into TDocente values('912621','YESHICA ISELA','ORMEÑO AYALA','NOMBRADO','INGENIERIA INFORMATICA')
go

-------------------------------------------------------------------
-- inserción de datos en la tabla Requisito --
-------------------------------------------------------------------
insert into TRequisito values('REQ000001','CARTA DE ACEPTACION DE ASESOR')
insert into TRequisito values('REQ000004','PAGO POR DERECHO A TRAMITE')
insert into TRequisito values('REQ000009','SOLICITUD DIRIGIDA AL RECTOR')
insert into TRequisito values('REQ000010','FICHA DE SEGUIMIENTO ACADEMICO')
insert into TRequisito values('REQ000011','03 EJEMPLARES DE PLAN DE TESIS')

insert into TRequisito values('REQ000003','INFORME DE ASESOR(ES)')
insert into TRequisito values('REQ000005','EJEMPLARES ANILLADOS DE TESIS')




go
-------------------------------------------------------------------
-- inserción de datos en la tabla TipoTramite --
-------------------------------------------------------------------
insert into TTipoTramite values('TR000001','INSCRIPCION DE TESIS')--ENTREGA
insert into TTipoTramite values('TR000002','DICTAMEN DE TESIS')--PONER A DICTAMEN
insert into TTipoTramite values('TR000003','SUSTENTACION ORAL DE TESIS')--SOLOICITAR SUSTENTACION
go
-------------------------------------------------------------------
-- inserción de datos en la tabla TTipoTramite_Requisito --
-------------------------------------------------------------------
insert into TTipoTramite_Requisitos(CodTipoTramite, CodRequisito) values('TR000001','REQ000009')
insert into TTipoTramite_Requisitos(CodTipoTramite, CodRequisito) values('TR000001','REQ000010')
insert into TTipoTramite_Requisitos(CodTipoTramite, CodRequisito) values('TR000001','REQ000001')
insert into TTipoTramite_Requisitos(CodTipoTramite, CodRequisito) values('TR000001','REQ000011')
insert into TTipoTramite_Requisitos(CodTipoTramite, CodRequisito) values('TR000001','REQ000004')

insert into TTipoTramite_Requisitos(CodTipoTramite, CodRequisito) values('TR000002','REQ000003')
insert into TTipoTramite_Requisitos(CodTipoTramite, CodRequisito) values('TR000002','REQ000005')
go

-- insertar regitro de tesis--
--insertar tesis--
insert into TTesis values('T000001','INTELIGENCIA ARTIFICIAL','981565')


insert into TTesista_Tesis values('184209','T000001')
insert into TTesista_Tesis values('170430','T000001')


--insertar el expediente
insert into TExpediente values('E000001','09/02/2021','PROCESO','T000001','TR000001')
--insert into TExpediente values('E003251','10/02/2021','PROCESO','T000001','TR000003')

--- insertar asignacion de revisores-------
-- insertar expediente asignacion
insert into TExpedienteAsignacion values('EA000001','10/02/2021','E000001')
--insert into TExpedienteAsignacion values('EA002221','20/02/2021','E003251')

-- insertar expediente asignacion con docente
insert into TExpedienteAsig_Docente values('EA000001','981565','REVISOR')
insert into TExpedienteAsig_Docente values('EA000001','981626','REVISOR')


--insert into TExpedienteAsig_Docente values('EA002221','901054','REVISOR')
--insert into TExpedienteAsig_Docente values('EA002221','912321','REVISOR')
--insert into TExpedienteAsig_Docente values('EA002221','923544','REVISOR')


----- Insertar Evaluacion de Revisores---
insert into TInformeEvaluacion values('IE000001','INSCRIPCION DE TESIS','14/02/2021','','981565','4.0','APROBADO','E000001')
insert into TInformeEvaluacion values('IE000002','INSCRIPCION DE TESIS','14/02/2021','','981626','4.3','APROBADO','E000001')

------ Insertar RESOLUCION-------
--insert into TResolucion values('R000001','INSCRIPCION DE TESIS','16/02/2021','APROBADO','E000001')


--PROCESOS ALMACENADOS
go
create procedure spuListarAsignaciones
as
begin
	select distinct *--EA.CodExpedienteAsignacion as 'Código Asignación',T.CodTesis as 'Código Tesis', T.Titulo,TD.Nombres,TD.Apellidos
					from TExpedienteAsignacion EA  left join TExpedienteAsig_Docente EAD ON EA.CodExpedienteAsignacion = EAD.CodExpedienteAsignacion 
					inner join TExpediente E ON EA.CodExpediente = E.CodExpediente
					inner join TTesis T ON E.CodTesis = T.CodTesis 
					inner join TTesista_Tesis TT ON T.CodTesis = TT.CodTesis 
					inner join TTesista TE ON TT.CodAlumno = TE.CodAlumno
					inner join TDocente TD ON EAD.CodDocente = TD.CodDocente
end

go
create procedure spuListarExpedientesParaRevisores
as
begin
		select A.CodExpediente AS Codigo_Expediente,A.CodTesis AS Codigo_de_Tesis,B.Titulo as Titulo,A.Estado,C.Nombre as Tramite
		from TExpediente A inner join TTesis B on A.CodTesis=B.CodTesis
							inner join TTipoTramite C ON A.CodTipoTramite=C.CodTipoTramite
		where A.Estado='PROCESO' and A.CodTipoTramite='TR000001'
end
go

create procedure spuListarExpedientesParaPonerADictamen
as
begin
		select A.CodExpediente as Codigo_Expediente,B.CodTesis AS Codigo_de_Tesis,B.Titulo as Titulo
		from TExpediente A inner join TTesis B on A.CodTesis=B.CodTesis
							inner join TTipoTramite C ON A.CodTipoTramite=C.CodTipoTramite
							INNER JOIN TResolucion D on D.CodExpediente=A.CodExpediente
		where A.Estado='FINALIZADO' and A.CodTipoTramite='TR000001' AND D.NotaFinal='APROBADO'
end
go

create procedure spuListarExpedientesEvaluacionParaDictaminadores
as
begin
		select A.CodExpediente as Codigo_Expediente,B.CodTesis AS Codigo_de_Tesis,B.Titulo as Titulo,A.Estado,C.Nombre as Tramite
		from TExpediente A inner join TTesis B on A.CodTesis=B.CodTesis
							inner join TTipoTramite C ON A.CodTipoTramite=C.CodTipoTramite
		where A.Estado='PROCESO' and A.CodTipoTramite='TR000002'
end
go
create procedure spuListarExpedientesParaSustentacionOral
as
begin
		select A.CodExpediente as Codigo_Expediente,B.CodTesis AS Codigo_de_Tesis,B.Titulo as Titulo
		from TExpediente A inner join TTesis B on A.CodTesis=B.CodTesis
							inner join TTipoTramite C ON A.CodTipoTramite=C.CodTipoTramite
							INNER JOIN TResolucion D on D.CodExpediente=A.CodExpediente
		where A.Estado='FINALIZADO' and A.CodTipoTramite='TR000002' AND D.NotaFinal='SUFICIENTE'
end
go
create procedure spuListarExpedientesParaPonerActaSustentacion
as
begin
		select A.CodExpediente as Codigo_Expediente,C.CodTesis AS Codigo_de_Tesis,C.Titulo as Titulo,A.Estado,D.Nombre as Tramite
		from TExpediente A inner join TResolucionJurado B on A.CodExpediente=B.CodExpediente
							inner join TTesis C on A.CodTesis=C.CodTesis
							inner join TTipoTramite D on A.CodTipoTramite=D.CodTipoTramite
		where A.Estado='PROCESO' and A.CodTipoTramite='TR000003'
end
go

--------------------------------------------------------------------------
--Si usuario existe en la base de datos, LOGIN
create procedure spu_VerificarLogin (@Usuario varchar (20), @Contraseña varchar (20))
as
begin
select *
from TUsuarioAdministrativo U
where U.CodUsuario=@Usuario and U.Contraseña=@Contraseña
end
go
--EXAMEN
--mostrar toda la información referente a la inscripción de un tema de tesis específico
create procedure spu_ExpedientesSeguimientoInscripcion
as
begin
		select A.CodExpediente AS Codigo_Expediente,A.CodTesis AS Codigo_de_Tesis,B.Titulo as Titulo,A.Estado,C.Nombre as Tramite
		from TExpediente A inner join TTesis B on A.CodTesis=B.CodTesis
							inner join TTipoTramite C ON A.CodTipoTramite=C.CodTipoTramite
		where A.CodTipoTramite='TR000001'
end


--select *from TExpediente-- A inner join TExpediente B on A.CodExpedienteAsignacion
--select * from TTesista
--select * from TDocente
--select * from TRequisito
--select * from TTipoTramite
--select * from TTipoTramite_Requisitos
--select * from TTesista_Tesis
--select * from TInformeEvaluacion
--select * from TResolucion
--select * from TTesis
--select * from TInformeEvaluacion
--select * from TExpediente
--select * from TExpedienteAsignacion 
--select * from TExpedienteAsig_Docente
--SELECT * FROM TActaSustentacion
--select * from TTesista
go
create procedure spu_MostrarSeguimiento(@CodTesis varchar (10))
as
begin
select distinct A.CodExpediente as CodigoExpediente,A.Fecha as FechaInscripcion,B.Titulo,D.CodAlumno AS CodigoAlumno,D.Nombres,D.Apellidos,A.Estado
		from TExpediente A inner join TTesis B on A.CodTesis=B.CodTesis
							INNER JOIN TTesista_Tesis C on B.CodTesis=C.CodTesis
							inner join TTesista D on C.CodAlumno=D.CodAlumno
							LEFT join TInformeEvaluacion E on A.CodExpediente=E.CodExpediente
		where A.CodTipoTramite='TR000001' and B.CodTesis=@CodTesis
end
go

--exec spu_MostrarSeguimiento @CodTesis = 'T000001'